# Generated by Django 5.1.7 on 2025-04-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
    ]
