# Generated by Django 5.1.7 on 2025-04-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='next_of_kin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_as_next_of_kin', to='users.contact'),
        ),
    ]
