# Generated by Django 5.1.7 on 2025-03-18 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contributionsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date_contributed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
