# Generated by Django 5.1.7 on 2025-03-18 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_alter_contribution_recorded_by_contributionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date_contributed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
