# Generated by Django 5.1.7 on 2025-04-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_alter_benefitrequest_amount_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitrequest',
            name='amount_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
