# Generated by Django 5.1.7 on 2025-04-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_alter_benefitrequest_amount_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitrequest',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
